#pragma once

namespace MessageType
{
	enum eType
	{
		DEFAULT,
		RECIPIENT_ADD,
		RECIPIENT_REMOVE,
		CALL,
		CHANNEL_NAME_CHANGE,
		CHANNEL_ICON_CHANGE,
		CHANNEL_PINNED_MESSAGE,
		USER_JOIN,
		GUILD_BOOST,
		GUILD_BOOST_TIER_1,
		GUILD_BOOST_TIER_2,
		GUILD_BOOST_TIER_3,
		CHANNEL_FOLLOW_ADD,
		GUILD_DISCOVERY_DISQUALIFIED = 14,
		GUILD_DISCOVERY_REQUALIFIED,
		GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING,
		GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING,
		THREAD_CREATED,
		REPLY,
		CHAT_INPUT_COMMAND,
		THREAD_STARTER_MESSAGE,
		GUILD_INVITE_REMINDER,
		CONTEXT_MENU_COMMAND,
		AUTO_MODERATION_ACTION,
		ROLE_SUBSCRIPTION_PURCHASE,
		INTERACTION_PREMIUM_UPSELL,
		STAGE_START,
		STAGE_END,
		STAGE_SPEAKER,
		STAGE_TOPIC = 31,
		GUILD_APPLICATION_PREMIUM_SUBSCRIPTION,

		GAP_UP = 60,
		GAP_DOWN,
		CANT_VIEW_MSG_HISTORY,
		GAP_AROUND,
		NO_PINNED_MESSAGES,
		LOADING_PINNED_MESSAGES,
		UNSENT_MESSAGE,
		SENDING_MESSAGE,
		CHANNEL_HEADER,
	};
}
