//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDI_ICON                        1
#define IDI_SEND                        2
#define IDI_FILE                        3
#define IDI_ICON_SMALL                  4
#define IDI_WARNING_IC                  5
#define IDI_CATEGORY                    6
#define IDI_CHANNEL                     7
#define IDI_DM                          8
#define IDI_GROUPDM                     9
#define IDI_VOICE                       10
#define IDI_PROFILE_BORDER              11
#define IDI_OFFLINE_SM                  12
#define IDI_ONLINE_SM                   13
#define IDI_MENTION_MARKER_1            14
#define IDI_MENTION_MARKER_2            15
#define IDI_MENTION_MARKER_3            16
#define IDI_MENTION_MARKER_4            17
#define IDI_MENTION_MARKER_5            18
#define IDI_MENTION_MARKER_6            19
#define IDI_MENTION_MARKER_7            20
#define IDI_MENTION_MARKER_8            21
#define IDI_MENTION_MARKER_9            22
#define IDI_MENTION_MARKER_9P           23
#define IDI_CHANNEL_MENTIONED           24
#define IDI_CHANNEL_UNREAD              25
#define IDI_PIN                         26
#define IDI_MEMBERS                     27
#define IDI_BOT                         28
#define IDI_REPLY_PIECE                 29
#define IDI_USER_JOIN                   30
#define IDI_USER_LEAVE                  31
#define IDI_TYPING_FRAME1               32
#define IDI_TYPING_FRAME2               33
#define IDI_TYPING_FRAME3               34
#define IDI_TYPING_FRAME1_2K            35
#define IDI_TYPING_FRAME2_2K            36
#define IDI_TYPING_FRAME3_2K            37
#define IDI_UPLOAD                      38
#define IDI_DOWNLOAD                    39
#define IDI_CANCEL                      40
#define IDI_JUMP                        41
#define IDI_PROFILE_BORDER_2K           42
#define IDI_CHANNEL_2K                  43
#define IDI_MEMBERS_2K                  44
#define IDI_PIN_2K                      45
#define IDI_CATEGORY_2K                 46
#define IDI_DM_2K                       47
#define IDI_GROUPDM_2K                  48
#define IDI_VOICE_2K                    49
#define IDI_CHANNEL_MENTIONED_2K        50
#define IDI_CHANNEL_UNREAD_2K           51
#define IDI_FILE_2K                     52
#define IDI_BOT_2K                      53
#define IDI_STATUS_ONLINE               54
#define IDI_STATUS_IDLE                 55
#define IDI_STATUS_DND                  56
#define IDI_STATUS_OFFLINE              57
#define IDI_PROFILE_BORDER_GOLD         58
#define IDI_PROFILE_BORDER_GOLD_2K      59
#define IDI_JUMP_2K                     60
#define IDI_SEND_2K                     61
#define IDI_REPLY_PIECE_2K              62
#define IDI_WAIT                        63
#define IDI_IMAGE_ERROR                 64
#define IDI_BALLOON                     65
#define IDI_BALLOON_OFF                 66
#define IDI_SERVER                      67
#define IDI_SERVER_2K                   68
#define IDI_CATEGORY_COLLAPSE           71
#define IDI_ICON2                       72
#define IDI_CATEGORY_EXPAND             72
#define IDB_TARGET                      200
#define IDB_CHANNEL                     201
#define IDB_CATEGORY                    202
#define IDB_VOICE                       203
#define IDB_PROFILE                     204
#define IDB_DEFAULT                     205
#define IDB_DM                          206
#define IDB_GROUPDM                     207
#define IDB_STATUS_OFFLINE              208
#define IDB_STATUS_DND                  209
#define IDB_STATUS_IDLE                 210
#define IDB_STATUS_ONLINE               211
#define IDB_STATUS_MASK_CIRC            212
#define IDB_STATUS_MASK_MOON            213
#define IDB_LOGON_BANNER                214
#define IDB_EMPTY                       215
#define IDC_ZOOMIN                      350
#define IDC_ZOOMOUT                     351
#define IDD_DIALOG_ABOUT                401
#define IDD_DIALOG_OPTIONS              402
#define IDD_DIALOG_MY_ACCOUNT           403
#define IDD_DIALOG_APPEARANCE           404
#define IDD_DIALOG_PROFILE_POPOUT       405
#define IDD_DIALOG_LOGON                406
#define IDD_DIALOG_QRCODELOGIN          407
#define IDD_DIALOG_INSTANT_INVITE       408
#define IDD_DIALOG_PINNEDMESSAGES       409
#define IDD_DIALOG_UPLOADFILES          410
#define IDD_DIALOG_QUICK_SWITCHER       411
#define IDD_DIALOG_CONNECTION           412
#define IDR_MAINMENU                    501
#define IDR_MESSAGE_CONTEXT             502
#define IDR_GUILD_CONTEXT               503
#define IDR_CHANNEL_CONTEXT             505
#define IDR_DMCHANNEL_CONTEXT           506
#define IDS_PROGRAM_NAME                601
#define IDS_MY_ACCOUNT                  602
#define IDS_WELCOME_MSG                 603
#define IDS_PRIVACY_SAFETY              604
#define IDS_MESSAGE_TOO_LONG_MSG        605
#define IDS_DMBLOCK_APPLY_RETROACTIVELY 606
#define IDS_NOTLOGGEDIN                 607
#define IDS_APPEARANCE                  608
#define IDS_LOG_OUT                     609
#define IDS_SESSION_ERROR               610
#define IDS_CONNECT_FAILURE             611
#define IDS_ACCOUNT_PRIVACY             612
#define IDS_DANGEROUS_DOWNLOAD          613
#define IDS_DANGEROUS_DOWNLOAD_TITLE    614
#define IDS_PLEASE_WAIT                 615
#define IDS_LOADING_MESSAGES            616
#define IDS_CHANGED_GROUP_ICON          617
#define IDS_CHANGED_CHANNEL_NAME_L      618
#define IDS_CHANGED_CHANNEL_NAME_R      619
#define IDS_REMOVED_FROM_GROUP          620
#define IDS_ADDED_TO_GROUP              621
#define IDS_PINNED_MESSAGE              622
#define IDS_WELCOME_001_R               623
#define IDS_WELCOME_002_R               624
#define IDS_WELCOME_003_L               625
#define IDS_WELCOME_003_R               626
#define IDS_WELCOME_004_L               627
#define IDS_WELCOME_004_R               628
#define IDS_WELCOME_005_R               629
#define IDS_WELCOME_006_R               630
#define IDS_WELCOME_007_R               631
#define IDS_WELCOME_008_L               632
#define IDS_WELCOME_008_R               633
#define IDS_WELCOME_009_R               634
#define IDS_WELCOME_010_L               635
#define IDS_WELCOME_011_L               636
#define IDS_WELCOME_012_L               637
#define IDS_WELCOME_013_L               638
#define IDS_WELCOME_EXCLAM              639
#define IDS_WELCOME_PERIOD              640
#define IDS_SAVE_IMAGE                  641
#define IDS_SAVE_FILE_AS_TITLE          642
#define IDS_ERROR_ACCESSING_FILE        643
#define IDS_ERROR_SAVING_FILE           644
#define IDS_IMAGE_SAVING                645
#define IDS_IMAGE_SAVED                 646
#define IDS_TOKEN_TOO_LONG              647
#define IDS_TOKEN_TOO_SHORT             648
#define IDS_LOGIN_NO_INTERNET           649
#define IDS_TODAY_AT                    650
#define IDS_YESTERDAY_AT                651
#define IDS_LONG_DATE_FMT               652
#define IDS_SHORT_DATE_FMT              653
#define IDS_ONLY_DATE_FMT               654
#define IDS_MONTH_JANUARY               655
#define IDS_MONTH_FEBRUARY              656
#define IDS_MONTH_MARCH                 657
#define IDS_MONTH_APRIL                 658
#define IDS_MONTH_MAY                   659
#define IDS_MONTH_JUNE                  660
#define IDS_MONTH_JULY                  661
#define IDS_MONTH_AUGUST                662
#define IDS_MONTH_SEPTEMBER             663
#define IDS_MONTH_OCTOBER               664
#define IDS_MONTH_NOVEMBER              665
#define IDS_MONTH_DECEMBER              666
#define IDS_CANT_VIEW_CHANNEL           667
#define IDS_CANT_VIEW_MESSAGE_HISTORY   668
#define IDS_CANT_SEND_MESSAGES          669
#define IDS_SHORT_TIME_FMT              670
#define IDS_CONFIRM_DELETE              671
#define IDS_CONFIRM_DELETE_TITLE        672
#define IDS_CONFIRM_PIN                 673
#define IDS_CONFIRM_PIN_TITLE           674
#define IDS_DIRECT_MESSAGES             675
#define IDS_LINK_CONFIRM                676
#define IDS_HOLD_UP_CONFIRM             677
#define IDS_LOADING_PINNED_MESSAGES     678
#define IDS_NO_PINNED_MESSAGES          679
#define IDS_PINNED_MESSAGES_IN          680
#define IDS_CONFIRM_LEAVE_GUILD         681
#define IDS_FAILED_TO_INITIALIZE_SAPI   682
#define IDS_FAILED_TO_INITIALIZE_SAPI_TITLE 683
#define IDS_FAILED_TO_SPEAK_MESSAGE     684
#define IDS_CANNOT_UPLOAD_ATTACHMENT    685
#define IDS_FILE_TOO_BIG                686
#define IDS_FILE_EMPTY                  687
#define IDS_FILE_OUT_OF_MEMORY          688
#define IDS_FILE_NO_OPEN                689
#define IDS_FILE_NO_READ                690
#define IDS_CONNECTION                  691
#define IDS_URL_EMPTY                   692
#define IDS_CONFIRM_SET_URLS            693
#define IDS_CONFIRM_OFFICIAL_URLS       694
#define IDS_CHECK_UPDATES               695
#define IDS_NEW_VERSION_AVAILABLE       696
#define IDS_FAILED_UPDATE_CHECK         697
#define IDS_FAILED_TO_UPLOAD            698
#define IDS_SAVED_UPDATE                699
#define IDS_MAY_CONTAIN_TOKEN           700
#define IDC_OPTIONS_TABS                801
#define IDC_MY_ACCOUNT_BOX              802
#define IDC_MY_ACCOUNT_NAME             803
#define IDC_EMAIL_DISPLAY               804
#define IDC_EMAIL_TEXT                  805
#define IDC_REVEALEMAIL                 806
#define IDC_SDM_LEVEL0                  807
#define IDC_SDM_LEVEL1                  808
#define IDC_SDM_LEVEL2                  809
#define IDC_ENABLE_DMS                  810
#define IDC_LOG_OUT                     811
#define IDC_MDISPLAY_BOX                812
#define IDC_APPEARANCE_COZY             813
#define IDC_APPEARANCE_COMPACT          814
#define IDC_MSTYLE_BOX                  815
#define IDC_GLOBAL_NAME                 816
#define IDC_USERNAME                    817
#define IDC_PROFILE_STATUS              818
#define IDC_RADIO_3D_FRAME              819
#define IDC_RADIO_GRADIENT              820
#define IDC_ROLE_STATIC                 820
#define IDC_RADIO_FLAT_1                821
#define IDC_RADIO_FLAT_2                822
#define IDC_STATIC_PROFILE_IMAGE        823
#define IDC_MEMBERSINCEGROUP            824
#define IDC_GUILD_JOIN_DATE             825
#define IDC_DISCORD_JOIN_DATE           826
#define IDC_ICON_GUILD                  827
#define IDC_ICON_DISCORD                828
#define IDC_ROLE_GROUP                  829
#define IDC_EDIT_TOKEN                  830
#define IDC_NOTE_GROUP                  831
#define IDC_NOTE_TEXT                   832
#define IDC_MESSAGE_GROUP               833
#define IDC_MESSAGE_TEXT                834
#define IDC_LOGON_BANNER                835
#define IDC_LBL_EMAIL                   836
#define IDC_LBL_PASSWORD                837
#define IDC_EDIT_EMAIL                  838
#define IDC_EDIT_PASSWORD               839
#define IDC_NUM_ONLINE                  840
#define IDC_RADIO_EMAILPASS             841
#define IDC_RADIO_TOKEN                 842
#define IDC_ICON_WARN_CAPTCHA           843
#define IDC_WARN_CAPTCHA                844
#define IDC_LOGIN_QR_CODE               845
#define IDC_LBL_LOGINQR                 846
#define IDC_QRCODE_PLACEHOLDER          847
#define IDC_INVITE_GUILD_IMAGE          848
#define IDC_GUILD_NAME                  849
#define IDC_NUM_MEMBERS                 851
#define IDC_MESSAGE_LIST                852
#define IDC_FILE_ICON                   853
#define IDC_FILE_NAME                   854
#define IDC_CHANNEL_NAME                855
#define IDC_ATTACH_COMMENT              856
#define IDC_MARK_AS_SPOILER             857
#define IDC_PROGRAM_NAME                858
#define IDC_SAVE_WINDOW_SIZE            859
#define IDC_START_MAXIMIZED             860
#define IDC_QUICK_QUERY                 861
#define IDC_CHANNEL_LIST                862
#define IDC_QUICK_GROUP                 863
#define IDC_EDIT_DISCORDAPI             864
#define IDC_EDIT_DISCORDCDN             865
#define IDC_REVERTTODEFAULT             866
#define IDC_UPDATE                      867
#define IDC_ICON_WARN_CONNECT           868
#define IDC_ICON_WARN_WEBSOCKETSTUFF    869
#define IDC_ICON_WARN_WEBSOCKETSTUFF2   870
#define IDC_CHECK1                      871
#define IDC_ENABLE_TLS_CHECKS           871
#define IDC_CHECK_UPDATES               872
#define ID_FILE_PREFERENCES             1001
#define ID_FILE_STOPALLSPEECH           1002
#define ID_FILE_EXIT                    1003
#define ID_SERVER_SERVERBOOST           1004
#define ID_SERVER_INVITEPEOPLE          1005
#define ID_SERVER_SERVERSETTINGS        1006
#define ID_SERVER_NOTIFICATIONSETTINGS  1007
#define ID_SERVER_PRIVACYSETTINGS       1008
#define ID_SERVER_EDITSERVERPROFILE     1009
#define ID_SERVER_HIDEMUTEDCHANNELS     1010
#define ID_SERVER_LEAVESERVER           1011
#define ID_ACTIONS_SEARCH               1012
#define ID_ACTIONS_NEWGROUPDM           1013
#define ID_ACTIONS_ADDFRIEND            1014
#define ID_ONLINESTATUSPLACEHOLDER_ONLINE 1015
#define ID_ONLINESTATUSPLACEHOLDER_IDLE 1016
#define ID_ONLINESTATUSPLACEHOLDER_DONOTDISTURB 1017
#define ID_ONLINESTATUSPLACEHOLDER_INVISIBLE 1018
#define ID_ACCOUNT_SETCUSTOMSTATUS      1019
#define ID_ACCOUNT_SWITCHACCOUNTS       1020
#define ID_ACCOUNT_UNMUTE               1021
#define ID_ACCOUNT_DEAFEN               1022
#define ID_ACCOUNT_USERSETTINGS         1023
#define ID_HELP_HELPTOPICS              1024
#define ID_HELP_ABOUTDISCORDMESSENGER   1025
#define ID_ADDREACTION_REACTION1        1026
#define ID_ADDREACTION_REACTION2        1027
#define ID_ADDREACTION_REACTION3        1028
#define ID_ADDREACTION_REACTION4        1029
#define ID_ADDREACTION_REACTION5        1030
#define ID_ADDREACTION_REACTION6        1031
#define ID_ADDREACTION_REACTION7        1032
#define ID_ADDREACTION_REACTION8        1033
#define ID_ADDREACTION_VIEWMORE         1034
#define ID_DUMMYPOPUP_EDITMESSAGE       1035
#define ID_DUMMYPOPUP_PINMESSAGE        1036
#define ID_DUMMYPOPUP_REPLY             1037
#define ID_DUMMYPOPUP_COPYTEXT          1038
#define ID_DUMMYPOPUP_MARKUNREAD        1039
#define ID_DUMMYPOPUP_COPYMESSAGELINK   1040
#define ID_DUMMYPOPUP_SPEAKMESSAGE      1041
#define ID_DUMMYPOPUP_DELETEMESSAGE     1042
#define ID_DUMMYPOPUP_COPYID            1043
#define IDM_MARKASREAD                  1044
#define IDM_INVITEPEOPLE                1045
#define IDM_MUTESERVER                  1046
#define IDM_NOTIFYALL                   1047
#define IDM_NOTIFYMENTS                 1048
#define IDM_NOTIFYNONE                  1049
#define IDM_NOTIFYSUPPRGLOB             1050
#define IDM_NOTIFYSUPPRROLE             1051
#define IDM_GUILDSETTINGS               1052
#define IDM_PRIVACYSETTINGS             1053
#define IDM_EDITNICKNAME                1054
#define IDM_CREATECHAN                  1055
#define IDM_CREATECATEG                 1056
#define IDM_LEAVEGUILD                  1057
#define IDM_COPYGUILDID                 1058
#define IDM_MUTECHANNEL                 1059
#define IDM_INSTANTINVITE               1060
#define IDM_COPYCHANID                  1061
#define IDM_PROFILE                     1062
#define IDM_CLOSEDM                     1063
#define IDM_ADDFRIEND                   1064
#define IDM_BLOCK                       1065
#define IDM_COPYID                      1066
#define ID_ACTIONS_QUICKSWITCHER        1067
#define IDR_MAIN_ACCELS                 1201
#define IDA_SEARCH                      1301
#define IDA_QUICKSWITCHER               1302
#define IDA_PASTE                       1303

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        73
#define _APS_NEXT_COMMAND_VALUE         1069
#define _APS_NEXT_CONTROL_VALUE         873
#define _APS_NEXT_SYMED_VALUE           40000
#endif
#endif
