#!/usr/bin/env python3
"""Writes src/motif/AppIcon.hpp: the 64x64 32-bit image of the app's icon
(res/icons/icon_discord.ico) as ARGB words, for the Motif client's window
icon.  Run from the repository's top directory after changing the icon."""
import struct

d = open('res/icons/icon_discord.ico', 'rb').read()
count = struct.unpack('<H', d[4:6])[0]
for i in range(count):
    w, h, _, _, _, bpp, size, off = struct.unpack('<BBBBHHII', d[6 + 16 * i:22 + 16 * i])
    if w == 64 and bpp == 32:
        break
else:
    raise SystemExit('no 64x64 32-bit image in the icon')

px = d[off + 40:off + 40 + 64 * 64 * 4]   # BITMAPINFOHEADER, then BGRA rows bottom-up
words = []
for y in range(64):
    row = px[(63 - y) * 256:(64 - y) * 256]
    for x in range(64):
        b, g, r, a = row[4 * x:4 * x + 4]
        words.append('0x%02x%02x%02x%02x' % (a, r, g, b))

with open('src/motif/AppIcon.hpp', 'w') as f:
    f.write('#pragma once\n\n')
    f.write('// The app icon (res/icons/icon_discord.ico, 64x64), ARGB.\n')
    f.write('// Generated by irix/make-app-icon.py: do not edit.\n\n')
    f.write('#include <cstdint>\n\n')
    f.write('static const int APP_ICON_SIZE = 64;\n')
    f.write('static const uint32_t g_appIcon[64 * 64] = {\n')
    for i in range(0, len(words), 8):
        f.write('\t' + ', '.join(words[i:i + 8]) + ',\n')
    f.write('};\n')
