name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OPENSSL_INSTALL: 'C:\OpenSSL-Win32'

jobs:
  windows-visual-studio:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install v141_xp build tools and Windows 10.0.22621.0 SDK
        shell: pwsh
        run: |
          $vs_path = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $vs_installer = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe"
          
          Start-Process "$vs_installer" -ArgumentList @(
            "modify",
            "--installPath", "C:\Program Files\Microsoft Visual Studio\2022\Community",
            "--add", "Microsoft.VisualStudio.VC.MSBuild.v150.x86.v141_xp",
            "--add", "Microsoft.VisualStudio.VC.MSBuild.v150.x64.v141_xp",
            "--add", "Microsoft.Component.VC.Runtime.UCRTSDK",
            "--add", "Microsoft.VisualStudio.VC.IDE.Project.Factories",
            "--add", "Microsoft.VisualStudio.Component.VC.v141.x86.x64",
            "--add", "Microsoft.VisualStudio.Component.WinXP",
            "--add", "Microsoft.VisualStudio.Component.VC.v141.x86.x64",
            "--add", "Microsoft.VisualStudio.Component.Windows10SDK.22621",
            "--quiet"
            "--norestart"
          ) -Wait

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup OpenSSL
        run: |
          curl -Lo "openssl-prebuilt-msvc.zip" https://github.com/DiscordMessenger/openssl/releases/download/release-1-msvc/openssl-prebuilt-msvc.zip
          Expand-Archive -Path "openssl-prebuilt-msvc.zip" -DestinationPath "${{ env.OPENSSL_INSTALL }}" -Force

      - name: Get latest tag
        id: get-latest-tag
        run: Write-Output "TAG=$(git describe --abbrev=0 --tags)" >> $Env:GITHUB_OUTPUT

      - name: Build with Visual Studio
        run: msbuild vs\DiscordMessenger.sln /p:Configuration=Release /p:Platform=x86 /p:OPENSSL_INSTALL="${{ env.OPENSSL_INSTALL }}"

      - name: Copy required DLLs
        run: Copy-Item -Path "$env:OPENSSL_INSTALL\libcrypto-3.dll", "$env:OPENSSL_INSTALL\libssl-3.dll" -Destination "bin\Release" -Force

      - uses: actions/upload-artifact@v4
        with:
          name: 'DiscordMessenger-${{ steps.get-latest-tag.outputs.TAG }}-MSVC'
          path: |
            bin\Release\DiscordMessenger.exe
            bin\Release\*.dll
            bin\Release\*.pdb
