name: Build (MinGW)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OPENSSL_DIR: '/tmp/dm-openssl'
  LIBWEBP_DIR: '/tmp/dm-libwebp/build'

jobs:
  build-linux-mingw:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Install Compiler Tools
        run: sudo apt install mingw-w64 gcc-mingw-w64-x86-64-posix g++-mingw-w64-x86-64-posix
      
      - name: Download OpenSSL
        run: |
          curl -Lo "openssl-stuff.zip" https://github.com/DiscordMessenger/openssl/releases/download/release-1/openssl-stuff.zip
          mkdir -p $OPENSSL_DIR
          unzip openssl-stuff.zip -d $OPENSSL_DIR
      
      - name: Get Latest Tag
        id: get-latest-tag
        run: |
            echo "TAG=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"
            echo "COMMIT=$(git rev-parse --short=8 HEAD)" >> "$GITHUB_OUTPUT"
      
      - name: Compile Libwebp
        run: |
            git clone https://github.com/DiscordMessenger/libwebp.git /tmp/dm-libwebp
            cd /tmp/dm-libwebp
            mkdir build && cd build
            cmake .. -DCMAKE_TOOLCHAIN_FILE=../win32.cmake
            make -j12
      
      - name: Make Unicode Build
        run: make DEBUG=no UNICODE=yes COMMIT_HASH=${{ steps.get-latest-tag.outputs.COMMIT }} -j$(nproc)
      
      - name: Upload Unicode Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'DiscordMessenger-${{ steps.get-latest-tag.outputs.TAG }}-PRE-MinGW'
          path: bin/DiscordMessenger.exe
      
      - name: Make ANSI Build
        run: |
          rm -rf build
          CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ WR=i686-w64-mingw32-windres EXTRA_FLAGS="-static-libstdc++ -static-libgcc -Wl,--no-whole-archive" DEBUG=no UNICODE=no make -j$(nproc)
      
      - name: Upload ANSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'DiscordMessenger-${{ steps.get-latest-tag.outputs.TAG }}-PRE-MinGWA'
          path: bin/DiscordMessenger.exe

